export const sources = {
  pl: { name: 'Serwis Rzeczypospolitej Polskiej — polska flaga', url: 'https://powroty.gov.pl/-/co-warto-wiedziec-o-polskiej-fladze-i-barwach-narodowych-' },
  jp: { name: 'Ministerstwo Sprawiedliwości Japonii — ustawa o fladze', url: 'https://www.japaneselawtranslation.go.jp/en/laws/view/1386' },
  np: { name: 'The World Factbook — Nepal (archiwum)', url: 'https://www.cia.gov/the-world-factbook/about/archives/2021/countries/nepal/' },
  ca: { name: 'Rząd Kanady — opis flagi', url: 'https://www.canada.ca/en/canadian-heritage/services/flag-canada-description.html' },
  br: { name: 'The World Factbook — Brazylia (archiwum)', url: 'https://www.cia.gov/the-world-factbook/about/archives/2021/countries/brazil/' },
  za: { name: 'Rząd RPA — flaga narodowa', url: 'https://www.gov.za/about-sa/national-flag' },
  gb: { name: 'The Royal Family — Union Jack', url: 'https://www.royal.uk/union-jack' },
  us: { name: 'USA.gov — flaga Stanów Zjednoczonych', url: 'https://www.usa.gov/flag' },
  ch: { name: 'Presence Switzerland — flaga Szwajcarii', url: 'https://www.aboutswitzerland.eda.admin.ch/en/swiss-flag' },
  kz: { name: 'The World Factbook — flaga Kazachstanu (archiwum)', url: 'https://www.cia.gov/the-world-factbook/about/archives/2022/countries/kazakhstan/flag' },
  bt: { name: 'Bhutan — National Flag Rules 1972', url: 'https://oag.gov.bt/wp-content/uploads/2011/02/National-Flag-Rules-1972-English.pdf' },
  tz: { name: 'The World Factbook — Tanzania (archiwum)', url: 'https://www.cia.gov/the-world-factbook/about/archives/2021/countries/tanzania/' },
  au: { name: 'Rząd Australii — Australian National Flag', url: 'https://www.pmc.gov.au/resources/australian-flags-booklet/part-1-australian-national-flag' },
  in: { name: 'National Portal of India — flaga narodowa', url: 'https://knowindia.india.gov.in/national-identity-elements/national-flag.php' },
  jm: { name: 'Jamaica Information Service — flaga Jamajki', url: 'https://jis.gov.jm/information/get-the-facts/the-jamaican-flag/' },
  kr: { name: 'Korea.net — Taegeukgi', url: 'https://www.korea.net/AboutKorea/OverviewofKorea' },
  nz: { name: 'Rząd Nowej Zelandii — flaga narodowa', url: 'https://www.mch.govt.nz/our-work/flags-anthems-and-emblems/new-zealand-flag' },
  gr: { name: 'Prezydent Grecji — flaga państwowa', url: 'https://www.presidency.gr/en/presidency/the-flag/' },
  mx: { name: 'Rząd Meksyku — historia flagi', url: 'https://www.gob.mx/bancodelbienestar/articulos/historia-de-la-bandera-de-mexico' },
  tr: { name: 'Ministerstwo Spraw Zagranicznych Turcji — flaga', url: 'https://www.mfa.gov.tr/the-turkish-flag-and-the-turkish-national-anthem.en.mfa' },
  images: { name: 'Flagpedia / FlagCDN — pliki flag (public domain)', url: 'https://flagpedia.net/about' },
}

export const flags = [
  {
    code: 'pl', name: 'Polska', continent: 'Europa', year: '1919', ratio: '5:8', colors: ['biały', 'czerwony'],
    hook: 'Dwa pasy, ale cała historia herbu.',
    story: 'Biały pas pochodzi od Białego Orła, a czerwony od pola tarczy herbowej. Biel jest u góry, bo w heraldyce znak jest ważniejszy od tła.',
    symbols: ['Biel: Biały Orzeł', 'Czerwień: pole tarczy', '2 maja: Dzień Flagi'], sourceIds: ['pl'],
  },
  {
    code: 'jp', name: 'Japonia', continent: 'Azja', year: '1999', ratio: '2:3', colors: ['biały', 'czerwony'],
    hook: 'Czerwone koło to tarcza słońca.',
    story: 'Flaga nazywa się Nisshōki, a potocznie Hinomaru — „krąg słońca”. Ustawa z 1999 roku określa ją jako białą flagę z karmazynowym kołem pośrodku.',
    symbols: ['Koło: słońce', 'Białe pole', 'Nazwa: Hinomaru'], sourceIds: ['jp'],
  },
  {
    code: 'np', name: 'Nepal', continent: 'Azja', year: '1962', ratio: 'nietypowe', colors: ['karmazyn', 'niebieski', 'biały'],
    hook: 'Jedyna flaga państwa, która nie jest prostokątem.',
    story: 'Dwa trójkątne proporce łączą się w jedną flagę. Słońce i księżyc wyrażają nadzieję, że państwo przetrwa tak długo jak one.',
    symbols: ['Dwa proporce', 'Księżyc i słońce', 'Niebieska obwódka: pokój'], sourceIds: ['np'], record: 'Jedyna nieprostokątna flaga państwowa',
  },
  {
    code: 'ca', name: 'Kanada', continent: 'Ameryka Północna', year: '1965', ratio: '1:2', colors: ['czerwony', 'biały'],
    hook: 'Liść ma 11 punktów, żeby był czytelny na wietrze.',
    story: 'Pierwszy projekt liścia miał 13 punktów. Zmieniono go na 11, bo taki kształt łatwiej rozpoznać z daleka, gdy flaga faluje.',
    symbols: ['Liść klonu', '11 punktów', 'Pierwsze podniesienie: 1965'], sourceIds: ['ca'],
  },
  {
    code: 'br', name: 'Brazylia', continent: 'Ameryka Południowa', year: '1889', ratio: '7:10', colors: ['zielony', 'żółty', 'niebieski', 'biały'],
    hook: 'Na fladze jest prawdziwa mapa gwiazd.',
    story: 'Niebieskie niebo pokazuje układ gwiazd nad Rio de Janeiro o poranku 15 listopada 1889 roku. Dziś 27 gwiazd oznacza 26 stanów i Dystrykt Federalny.',
    symbols: ['27 gwiazd', 'Ordem e Progresso', 'Niebo nad Rio'], sourceIds: ['br'],
  },
  {
    code: 'za', name: 'Republika Południowej Afryki', continent: 'Afryka', year: '1994', ratio: '2:3', colors: ['czerwony', 'niebieski', 'zielony', 'czarny', 'biały', 'żółty'],
    hook: 'Kształt Y opowiada o łączeniu różnych dróg.',
    story: 'Flagę zaprojektował Fred Brownell i po raz pierwszy użyto jej 27 kwietnia 1994 roku. Rząd RPA podkreśla, że kolorom nie należy przypisywać jednego uniwersalnego znaczenia.',
    symbols: ['Y: zbieganie się dróg', '6 kolorów', 'Pierwszy dzień: 27.04.1994'], sourceIds: ['za'],
  },
  {
    code: 'gb', name: 'Wielka Brytania', continent: 'Europa', year: '1801', ratio: '1:2', colors: ['czerwony', 'biały', 'niebieski'],
    hook: 'Trzy krzyże nałożone na siebie.',
    story: 'Union Jack łączy krzyże św. Jerzego, św. Andrzeja i św. Patryka. Walia nie ma osobnego znaku, bo przy pierwszym połączeniu flag w 1606 roku była już złączona z Anglią.',
    symbols: ['Anglia: krzyż prosty', 'Szkocja: biały skos', 'Irlandia: czerwony skos'], sourceIds: ['gb'],
  },
  {
    code: 'us', name: 'Stany Zjednoczone', continent: 'Ameryka Północna', year: '1960', ratio: '10:19', colors: ['czerwony', 'biały', 'niebieski'],
    hook: '50 gwiazd i 13 pasów — nic tu nie jest przypadkiem.',
    story: '50 gwiazd oznacza 50 stanów, a 13 pasów — 13 pierwszych kolonii. Obecny układ obowiązuje od 4 lipca 1960 roku, po dołączeniu Hawajów.',
    symbols: ['50 gwiazd', '13 pasów', 'Ostatnia zmiana: 1960'], sourceIds: ['us'],
  },
  {
    code: 'ch', name: 'Szwajcaria', continent: 'Europa', year: '1848', ratio: '1:1', colors: ['czerwony', 'biały'],
    hook: 'Jedna z dwóch kwadratowych flag państwowych.',
    story: 'Biały krzyż na czerwonym tle stał się oficjalną flagą w 1848 roku. Kwadratowy kształt wyróżnia ją razem z flagą Watykanu.',
    symbols: ['Kwadrat 1:1', 'Biały krzyż', 'Korzenie znaku: XIV wiek'], sourceIds: ['ch'], record: 'Kwadrat zamiast prostokąta',
  },
  {
    code: 'kz', name: 'Kazachstan', continent: 'Azja', year: '1992', ratio: '1:2', colors: ['błękitny', 'złoty'],
    hook: 'Słońce ma 32 promienie w kształcie ziaren.',
    story: 'Pod słońcem leci orzeł stepowy. Przy maszcie biegnie złoty wzór „baranie rogi”, a błękit ma przypominać niebo i jedność.',
    symbols: ['32 promienie', 'Orzeł stepowy', 'Wzór koshkar-muiz'], sourceIds: ['kz'],
  },
  {
    code: 'bt', name: 'Bhutan', continent: 'Azja', year: '1969', ratio: '2:3', colors: ['żółty', 'pomarańczowy', 'biały'],
    hook: 'Biały smok trzyma klejnoty.',
    story: 'Bhutan nazywa siebie Druk Yul — Krainą Grzmiącego Smoka. Żółty oznacza świecką tradycję, pomarańczowy duchową, a biały smok czystość myśli ludzi.',
    symbols: ['Druk: smok', 'Żółty: tradycja świecka', 'Pomarańczowy: tradycja duchowa'], sourceIds: ['bt'],
  },
  {
    code: 'tz', name: 'Tanzania', continent: 'Afryka', year: '1964', ratio: '2:3', colors: ['zielony', 'niebieski', 'czarny', 'żółty'],
    hook: 'Ukośny pas łączy kolory lądu i oceanu.',
    story: 'Zielony kojarzy się z roślinnością, niebieski z oceanem i wodami, czarny z mieszkańcami, a złote brzegi z bogactwami ziemi.',
    symbols: ['Ukośny czarny pas', 'Zielony ląd', 'Niebieska woda'], sourceIds: ['tz'],
  },
  {
    code: 'au', name: 'Australia', continent: 'Oceania', year: '1901', ratio: '1:2', colors: ['niebieski', 'biały', 'czerwony'],
    hook: 'Na fladze znajdziesz Krzyż Południa.',
    story: 'Duża Gwiazda Wspólnoty ma siedem ramion: sześć stanów i terytoria. Pięć gwiazd po prawej pokazuje gwiazdozbiór widoczny na południowym niebie.',
    symbols: ['Union Jack', 'Gwiazda Wspólnoty', 'Krzyż Południa'], sourceIds: ['au'],
  },
  {
    code: 'gr', name: 'Grecja', continent: 'Europa', year: '1978', ratio: '2:3', colors: ['niebieski', 'biały'],
    hook: 'Dziewięć pasów i krzyż w rogu.',
    story: 'Flaga ma dziewięć naprzemiennych niebieskich i białych pasów. W kantonie — górnym rogu przy maszcie — znajduje się biały krzyż.',
    symbols: ['9 pasów', 'Krzyż w kantonie', 'Dwa kolory'], sourceIds: ['gr'],
  },
  {
    code: 'in', name: 'Indie', continent: 'Azja', year: '1947', ratio: '2:3', colors: ['szafranowy', 'biały', 'zielony', 'granatowy'],
    hook: 'Koło Aśoki ma dokładnie 24 szprychy.',
    story: 'Pośrodku białego pasa znajduje się granatowe koło — Aśoka Chakra. Projekt flagi przyjęto 22 lipca 1947 roku.',
    symbols: ['24 szprychy', '3 poziome pasy', 'Przyjęta w 1947'], sourceIds: ['in'],
  },
  {
    code: 'mx', name: 'Meksyk', continent: 'Ameryka Północna', year: '1968', ratio: '4:7', colors: ['zielony', 'biały', 'czerwony'],
    hook: 'Orzeł, wąż i kaktus tworzą całe godło.',
    story: 'W centrum flagi jest herb: orzeł na opuncji trzyma węża. Motyw nawiązuje do opowieści o miejscu założenia Tenochtitlán, dzisiejszego miasta Meksyk.',
    symbols: ['Orzeł', 'Wąż', 'Opuncja'], sourceIds: ['mx'],
  },
  {
    code: 'jm', name: 'Jamajka', continent: 'Ameryka Północna', year: '1962', ratio: '1:2', colors: ['czarny', 'zielony', 'złoty'],
    hook: 'Złoty krzyż po skosie nazywa się saltire.',
    story: 'Flagę po raz pierwszy podniesiono w dniu niepodległości, 6 sierpnia 1962 roku. Oficjalna myśl brzmi: słońce świeci, ziemia jest zielona, a ludzie silni i twórczy.',
    symbols: ['Złoty saltire', 'Zieleń: ziemia i nadzieja', 'Czerń: siła i twórczość'], sourceIds: ['jm'],
  },
  {
    code: 'tr', name: 'Turcja', continent: 'Azja', year: '1936', ratio: '2:3', colors: ['czerwony', 'biały'],
    hook: 'Półksiężyc i pięcioramienna gwiazda.',
    story: 'Biały półksiężyc i gwiazda stoją na czerwonym polu. Dokładny układ i proporcje flagi zostały zapisane w ustawie z 1936 roku.',
    symbols: ['Półksiężyc', 'Jedna gwiazda', 'Czerwone pole'], sourceIds: ['tr'],
  },
  {
    code: 'kr', name: 'Korea Południowa', continent: 'Azja', year: '1949', ratio: '2:3', colors: ['biały', 'czerwony', 'niebieski', 'czarny'],
    hook: 'Cztery czarne znaki opisują naturę.',
    story: 'Czerwono-niebieski taegeuk mówi o harmonii przeciwieństw. Cztery trygramy w rogach oznaczają niebo, ziemię, wodę i ogień.',
    symbols: ['Taegeuk: harmonia', '4 trygramy', 'Biel: pokój'], sourceIds: ['kr'],
  },
  {
    code: 'nz', name: 'Nowa Zelandia', continent: 'Oceania', year: '1902', ratio: '1:2', colors: ['niebieski', 'czerwony', 'biały'],
    hook: 'Cztery czerwone gwiazdy pokazują południowe niebo.',
    story: 'Gwiazdy tworzą Krzyż Południa i wskazują położenie Nowej Zelandii na południowym Pacyfiku. Union Jack przypomina o historii związanej z Wielką Brytanią.',
    symbols: ['4 gwiazdy', 'Krzyż Południa', 'Union Jack'], sourceIds: ['nz'],
  },
]

export const quizQuestions = [
  { code: 'np', prompt: 'Która flaga jako jedyna nie jest prostokątem ani kwadratem?', answer: 'Nepal', options: ['Nepal', 'Szwajcaria', 'Bhutan', 'Japonia'] },
  { code: 'ca', prompt: 'Ile punktów ma liść klonu na fladze Kanady?', answer: '11', options: ['7', '9', '11', '13'] },
  { code: 'br', prompt: 'Ile gwiazd jest na fladze Brazylii?', answer: '27', options: ['12', '24', '27', '50'] },
  { code: 'us', prompt: 'Co oznacza 13 pasów na fladze USA?', answer: '13 pierwszych kolonii', options: ['13 największych miast', '13 pierwszych kolonii', '13 prezydentów', '13 rzek'] },
  { code: 'in', prompt: 'Ile szprych ma Aśoka Chakra na fladze Indii?', answer: '24', options: ['12', '16', '24', '32'] },
  { code: 'za', prompt: 'W którym roku po raz pierwszy użyto obecnej flagi RPA?', answer: '1994', options: ['1962', '1989', '1994', '2001'] },
  { code: 'ch', prompt: 'Jaki kształt ma oficjalna flaga Szwajcarii?', answer: 'Kwadrat', options: ['Trójkąt', 'Kwadrat', 'Prostokąt 1:2', 'Pięciokąt'] },
  { code: 'kr', prompt: 'Co oznaczają cztery trygramy na fladze Korei Południowej?', answer: 'Niebo, ziemię, wodę i ogień', options: ['Cztery pory roku', 'Cztery miasta', 'Niebo, ziemię, wodę i ogień', 'Cztery języki'] },
]
